### ISSUE TITLE
I couldn't compile it in codespaces.

### ISSUE THREAD

**Issue by silvestrpredko** [inomotech-foss/aws-iot-device-sdk-rust#4]
Tells me that `AWS_LC` not belongs to the root project.
```log
package 'AWS_LC' didn't set the 'ROOT' variable in its build script or isn't a direct dependency of this package
```

**Comment by scootermon** [comment]
oh you're right, I forgot to test it on Linux after I switched from our own aws-lc bindings to the official ones provided by AWS.

**Comment by silvestrpredko** [comment]
> oh you're right, I forgot to test it on Linux after I switched from our own aws-lc bindings to the official ones provided by AWS.

It's not critical, I just created this issue to not forget to fix this.
